- hosts: webserver
  tasks:
    - name: Install Nginx
      become: true
      yum:
        name: "nginx"
        state: "{{ preferred_state }}"

      notify:
        - restart nginx


    - name: Install Nginx
      become: true
      service:
        name: nginx
        state: restarted
