---
- name: First playbook 
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
   - name: yum update
     yum:
       name: '*'
       state: latest  
     when: ansible_facts ['distribution'] in ['Amazon','RedHat']

   - name: apt update
     apt:
       name: '*'
       state: latest  
     when: ansible_facts ['distribution'] in ['Ubuntu']

- name: Nginx playbook 
  hosts: web
  become: yes
  gather_facts: yes
  tasks:
   - name: Manage Nginx on Amazon Linux
     yum:
       name: nginx
       state: {{ nginx_state }}   
     when: ansible_facts ['distribution'] in ['Amazon','RedHat']

   - name: Manage Nginx on Ubuntu Linux
     apt:
       name: nginx
       state: {{ nginx_state }}     
     when: ansible_facts ['distribution'] in ['Ubuntu']