---
- name: First playbook 
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
   - name: Show all gathered gather_facts
     debug:
       var: ansible_facts

   - name: yum update
     yum:
       name: '*'
       state: latest  
     when: ansible_facts ['distribution'] in ['Amazon','RedHat']
