---
- name: Nginx playbook 
  hosts: web
  become: yes
  gather_facts: yes
  tasks:
   - name: Manage Nginx on Amazon Linux
     yum:
       name: nginx
       state: "{{ nginx_state }}"  
     when: ansible_facts ['distribution'] in ['Amazon','RedHat']

   - name: Manage Nginx on Ubuntu Linux
     apt:
       name: nginx
       state: "{{ nginx_state }}"     
     when: ansible_facts ['distribution'] in ['Ubuntu']

   - name: Manage Nginx Service
     service:
       name: nginx
       state: started
     when: nginx_state == 'present' 